### ISSUE TITLE
Documentation of assumptions made by ikos

### ISSUE THREAD

**Issue by practicalswift** [NASA-SW-VnV/ikos#104]
What assumptions does `ikos` make?

Obviously we're assuming a standard compliant compiler but I'm thinking about assumptions regarding things such as data model/widths, signedness of `char`, IEC 559 (IEEE 754) floats, endianness, locale, etc which are not locked down by the spec.

Things such as:

```
std::numeric_limits<float>::is_iec559
std::numeric_limits<char>::is_signed
std::numeric_limits<unsigned char>::digits (CHAR_BIT)
std::endian::native
sizeof(float), sizeof(double), sizeof(long double)
sizeof(short), sizeof(int), sizeof(long), sizeof(long long)
sizeof(bool)
... etc ...
```

I'm both interested in a.) the assumptions made about the system that will run the program being analysed, and b.) the assumptions made about the system that will execute `ikos` itself.

**Comment by arthaud** [comment]
Hi @practicalswift,

I agree that we should document the assumptions make by IKOS.
The problem is that the information is scattered across the source code.
I'll need to write them iteratively, adding what comes to my mind at the time.

To answer your questions:

IKOS analyzes the LLVM bitcode generated by Clang. The LLVM bitcode is a generic assembly language, but it is target dependent. Thus, most of the things you asked about actually depend on Clang:

* Data Model: Clang defines a data layout depending on the target architecture. This is described in [LangRef.html#data-layout](https://llvm.org/docs/LangRef.html#data-layout). This is used to compute the size and alignment of all the types in the source code.
* Signedness of `char`: I believe Clang defines `char` as `signed`.
* IEC 559 (IEEE 754) floats: This is defined in [LangRef.html#t-floating](https://llvm.org/docs/LangRef.html#t-floating). IKOS does not reason about floating points right now.
* Endianness: see Data Model
* Locale: If I understand correctly, this is handled by the libc, and IKOS doesn't do any assumption about it.

```
std::numeric_limits<float>::is_iec559
std::numeric_limits<char>::is_signed
std::numeric_limits<unsigned char>::digits (CHAR_BIT)
std::endian::native
sizeof(float), sizeof(double), sizeof(long double)
sizeof(short), sizeof(int), sizeof(long), sizeof(long long)
sizeof(bool)
```
This is all compile time and thus is defined by Clang. It might depend on the target architecture.

> a.) the assumptions made about the system that will run the program being analysed

Here is a non-exhaustive list of assumptions made by IKOS:
* The program is single-threaded
* C library functions do not throw exceptions (see #30)
* Extern functions (function without implementation) do not write on global variables
* Extern functions can write on their pointer parameters, but only with one level of indirection
```c
extern void f(int** p); // assume to write on *p but not **p
```
* Extern functions do not call user-defined functions (no callbacks)
* Extern functions return well-initialized values
* Recursive function calls are treated as extern function calls
* Assembly codes are treated as extern function calls

> b.) the assumptions made about the system that will execute `ikos` itself.

IKOS itself is independent from the system that runs it.
But Clang is not, since it uses (by default) the host target, host abi and host libc headers.

**Comment by practicalswift** [comment]
> * Signedness of `char`: I believe Clang defines `char` as `signed`.

I think that it is dependent on the target architecture.

For `gcc` the following holds:
* `char` is signed: alpha, hppa, ia64, m68k, mips, sh, sparc, x86
* `char` is unsigned: arm, powerpc, s390

**Comment by arthaud** [comment]
Right, this is probably the same with clang.

**Comment by arthaud** [comment]
I added a section about the analysis assumptions in 593528ff3c9c6d4eb48393b2d9294187779f9610.
Would you like to add anything else or can I close this?

**Comment by practicalswift** [comment]
@arthaud Excellent! Thanks a lot. Closing!
