### ISSUE TITLE
Adding optimization causes failure

### ISSUE THREAD

**Issue by benjaminjellison** [NASA-SW-VnV/ikos#105]
I'm trying out your tool on a largish code base ([zstd](https://github.com/facebook/zstd)), and the default analysis takes a really long time.  I tried to use the optimization option to speed it up, but it instead breaks the program.  

Here is how I make it: ```LDFLAGS=-lpthread ~/ikos/install/bin/ikos-scan make```.  Note that if I don't include LDFLAGS part the build fails.  

Here is my command: ```~/ikos/install/bin/ikos -f json --report-verbosity 4 --report-file out.json --opt=aggressive programs/zstd.bc```

And here is the output:
```
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-0jmJ7w/zstd.pp.bc: error: invalid ar bitcast for llvm phi instruction
ikos: error: a run-time error occurred
```
I'm running on Ubuntu 16.04.  I really like the tool, it's very useful!  Thanks!

**Comment by arthaud** [comment]
Hi @benjaminjellison,

> Here is how I make it: `LDFLAGS=-lpthread ~/ikos/install/bin/ikos-scan make`. Note that if I don't include LDFLAGS part the build fails.

Is your library multithreaded? Unfortunately, IKOS doesn't handle multithreaded programs and will ignore calls to pthread.

> Here is my command: `~/ikos/install/bin/ikos -f json --report-verbosity 4 --report-file out.json --opt=aggressive programs/zstd.bc`

Using aggressive optimizations is not recommended. It basically runs LLVM passes to optimize the code, and thus will possible hide errors (undefined behaviors). It also sometimes generates instructions that are not supported by IKOS.

In this case, the error is because of the translation from LLVM to AR.

This is because of the following LLVM phi instruction:
```
{ i64, i64 } %.lcssa = phi { i64, i64 } [ %28, %53 ]
```

IKOS tries to infer the sign of integers since it is required by the analysis. It infers `{ui64, ui64}` for `%28` and `{si64, si64}` for `%53`, and `{si64, si64}` for the result `%.lcssa`. Since our bitcast instructions doesn't work on structures, there is no way to assign `%28` to `%.lcssa` in AR.

I don't think it is worth improving the error message since this is not something the user can fix.
We could add a warning about the usage of `--opt=aggressive` if you want.

By the way, you said the default analysis was slow. When did you stop the analysis? For a code of that size, it could take a few hours.

**Comment by benjaminjellison** [comment]
That's good to know about optimizations not being recommended.  An analysis on the order of hours is fine, I quit after less than an hour, not knowing how long it would take.  I think it would be good to put that optimizations are not recommended in the documentation.  I agree it's not worth improving the error message on the translation piece.  Thanks!
