### ISSUE TITLE
false negative on a simple code

### ISSUE THREAD

**Issue by mchalupa** [NASA-SW-VnV/ikos#109]
Hi,

when I run ikos (compiled from the current mastre) on the following code:

```C
int main(void) {
        int a = 2;
        if (a == 2)
                abort();
        return 0;
}
```

It tells me that both the `abort` and `return 0` are unreachable:

```
# Results
try.c: In function 'main':
try.c:4:3: unreachable: code is dead
		abort();
		^
try.c: In function 'main':
try.c:5:2: unreachable: code is dead
	return 0;
```

Tried with different domains and with/without optimizations.

**Comment by arthaud** [comment]
Thanks for the bug report. This is fixed in cceda919665a70debad28719ca1caff19ddf218d.

**Comment by Harvester57** [comment]
Isn't the code supposed to be reachable though ?

**Comment by mchalupa** [comment]
Yes, `abort()` should be reachable, `return 0` is unreachable.

**Comment by arthaud** [comment]
Yes, @mchalupa is right.

Here is the output of IKOS after the fix:
```
# Results
test.c: In function 'main':
test.c:5:9: unreachable: code is dead
        return 0;
        ^
```
This is correct since `abort()` is always called, and it never returns. The problem was that `abort()` was also reported as unreachable. This was because of the LLVM IR generated by clang:

```
define i32 @main() #0 !dbg !8 {
  call void @llvm.dbg.value(metadata i32 2, metadata !12, metadata !DIExpression()), !dbg !13
  %1 = icmp eq i32 2, 2, !dbg !14
  br i1 %1, label %2, label %3, !dbg !16

; <label>:2:                                      ; preds = %0
  call void @abort() #3, !dbg !17
  unreachable, !dbg !17

; <label>:3:                                      ; preds = %0
  ret i32 0, !dbg !18
}
```
After the call to `abort`, LLVM added an `unreachable` instruction. IKOS was reporting that this `unreachable` instruction is dead code. The debug information for this instruction points to the line of the call to `abort`, thus producing the bug.
To fix this, I am now skipping checks on `unreachable` instructions, since there is no actual code. If there is another instruction after an `unreachable`, it will be correctly reported as dead code.
