### ISSUE TITLE
Line numbers in warnings do not match source

### ISSUE THREAD

**Issue by kokke** [NASA-SW-VnV/ikos#12]
Hi guys,

For some of the projects I am scanning, warning line numbers do not match the source code. As an example, I can get a warning for line 465 in a file with less than 250 lines of code. Or the warning will be several lines below the stuff it warns about.

Here is an example: http://www.rowdy.dk/pics/warning.png
(the code shown is a part of STM32 standard peripheral library from STMicroelectronics for an ARM Cortex-M3 CPU)

My work-flow is this: 
I run clang over each .c file and finish with llvm-link to create a single file called whole_program.bc, which I then pass to IKOS. 

I assume IKOS gets line numbers from the LLVM bitcode, so it sounds like a problem with the LLVM-part of the toolchain. What do you think?

I tried using the wllvm-wrapper, but it doesn't change anything.

Do you have any good ideas for how to debug this issue?

**Comment by arthaud** [comment]
Hi @kokke,

Thanks for the bug report.

You are right, IKOS uses the source line numbers from the LLVM bitcode.

It is hard for me to understand the origin of the problem here without the source code and the LLVM bitcode.

I had a similar issue in the past, where LLVM was inlining a function call, but keeping the source line numbers. Within the same function, I was getting source lines from different files. This shouldn't be a problem now since we do NOT assume that all the statements of a function are within the same file. When reporting a bug on a statement, we use the debug information of the instruction to get the file, column and line.

Please make sure to compile your code in debug mode and without optimization. I recommend using: `clang -c -emit-llvm -D_FORTIFY_SOURCE=0 -g -O0`

If this doesn't fix your problem, I would need a short example reproducing the error, but I am guessing this will be hard to produce.

**Comment by kokke** [comment]
Hi @arthaud

I am already compiling with debug info and without optimization. I cannot easily recreate with smaller examples, but I will try and see if I can bisect the build to get a small example that still exhibits this behavior.

Most builds consist of 100-150 files and usually between 100k to 1M lines of preprocessed C code.

**Comment by kokke** [comment]
Hi @arthaud 

While bisecting I found the cause: Windows + Linux interop somehow add an extra newline in the preprocessing-step. I am guessing it comes from confusion between `\r\n` and `\n` as line-endings, but haven't found the culprit yet. It is entirely in the pre-processing step I am using.

Closing the issue, as it has nothing to do with either LLVM or IKOS.

Sorry to bother

**Comment by kokke** [comment]
The problem is my clang. It does not report proper line numbers if the lines endings are Windows-style carriage-return + linefeed / `\r\n` instead of just a linefeed / `\n`. 

Running the conversion tool `dos2unix` over the file before passing to clang fixes this problem.

I suspect it is also fixed in newer versions of clang - I cannot be the first to notice this :)

**Comment by arthaud** [comment]
Great catch! Thanks for reporting your findings, this could be helpful in the future.
