### ISSUE TITLE
Embedded targets: cross-compiling, multiple entrypoints, interrupt handlers

### ISSUE THREAD

**Issue by ttsiodras** [NASA-SW-VnV/ikos#123]
When analysing a codebase for an embedded target, what is the recommended workflow to address the embedded-world-specific challenges?

- The code is compiled via a cross-compiler; and may contain target-specific `__asm` blocks. In addition, passing  "-I" paths to the cross-includes won't suffice; there's plenty of default macros set in the cross-compilers that influence compilation. Is the `ikos-scan make` workflow applicable to such builds?
- Should we pass multiple --entry-point parameters, one with each ISR? And one more for the real entry point?
- Sometimes, SDKs for embedded targets come with a closed-source Board Support Package (BSP). This means that the code links with some libSuperSecretBSP.a library. Can ikos work interprocedurally in such a scenario - where partial functionality is missing - or does it need all of the code to properly function? 

Thanks in advance.

**Comment by arthaud** [comment]
Hi @ttsiodras,

>     * The code is compiled via a cross-compiler; and may contain target-specific `__asm` blocks. In addition, passing  "-I" paths to the cross-includes won't suffice; there's plenty of default macros set in the cross-compilers that influence compilation. Is the `ikos-scan make` workflow applicable to such builds?

For embedded systems using a cross-compiler, `ikos-scan` will probably not work, since it will try to compile and link with `clang`, which probably doesn't support the target architecture.

I usually use the given method: I create an alternative Makefile (e.g, `Makefile.llvm`), which compiles everything to llvm bitcode.
* First, I add the flag `-save-temps=obj` to the cross-compiler commands that generate the intermediate object files (i.e, `.o`). This will generate a preprocessed file `.i` for each `.o`.
* Then, I compile the `.i` files to llvm bitcode files `.bc` using `clang -c -emit-llvm -D_FORTIFY_SOURCE=0 -g -O0 -Xclang -disable-O0-optnone $(CFLAGS)`. I usually add this command in the Makefile target that creates the `.o` files.
* Then, I link all the `.bc` files together with `llvm-link`. I usually add this command in the target that creates the executable(s) and shared objects.

Running this `Makefile.llvm` generates a `.bc` for each executable, that you can analyze with `ikos`.

---

>     * Should we pass multiple --entry-point parameters, one with each ISR? And one more for the real entry point?

You could do that, but the analysis will be unsound. IKOS treats entry points as if they run in different processes. They don't share any memory or state.

IKOS currently doesn't handle interrupt handlers, and it would be complicated to implement. In the meantime, I think the best alternative is to create a function that calls interrupt handlers randomly, and call this function at a few specific places.

For instance:
```c
void handle_interrupts(void) {
  while (__ikos_nondet_int()) {
    if (__ikos_nondet_int()) {
      interrupt_handler_a();
    }
    if (__ikos_nondet_int()) {
      interrupt_handler_b();
    }
    // etc..
  }
}
```

Then, add a call to `handle_interrupts()` in your main loop. It still doesn't represent correctly the behavior of the program but I believe it is a good trade off.

---

>     * Sometimes, SDKs for embedded targets come with a closed-source Board Support Package (BSP). This means that the code links with some libSuperSecretBSP.a library. Can ikos work interprocedurally in such a scenario - where partial functionality is missing - or does it need all of the code to properly function?

IKOS will see calls to unknown extern functions. It makes a few assumptions about these functions:
* Extern functions do not update any global variable
* Extern functions might write on a given pointer parameter, but only with one level of indirection
```c
extern void f(int** p); // assume to write on *p but not **p
```
* Extern functions do not call user-defined functions (no callbacks)

In general these are good defaults.

You will also get a warning for each call to an unknown function. You can use `ikos-report --analyses-filter=sound output.db` to get only these warnings, and inspect them.

If a library function needs a special treatment, I usually write a small implementation for it, to simulate its behavior. We call this a "stub".

For instance, a stub for a library function `OS_mmap` could be:
```c
void* OS_mmap(void* addr, size_t len, int prot, int flags, int fd, off_t offset) {
  // (Optional) Check parameters
  __ikos_assert(addr == NULL);
  __ikos_assert(prot >= 0 && prot <= PROT_READ | PROT_WRITE | PROT_EXEC);
  __ikos_assert(fd >= 0);
  // mmap returns a (possibly-null) pointer to a block of memory, similar to malloc
  return malloc(len);
}
```

IKOS also provides helper functions to write these stubs, see https://github.com/NASA-SW-VnV/ikos/blob/master/analyzer/include/ikos/analyzer/intrinsic.h

Assembly code is treated the same way as a call to an unknown extern function. If your assembly code does not meet the assumptions above, you can also write a stub for them.

I hope this helps.

**Comment by ttsiodras** [comment]
Your detailed answer is very much appreciated - and perhaps deserves to exist as part of the documentation?

I can already report that step 1 of 3 worked fine on [my RTEMS scaffolds](https://gitrepos.estec.esa.int/ttsiodras/RTEMS-build-workflows/) - though the "dead code" reports appear to be... rather inaccurate.

Then of course IKOS has no awareness of things like these:

![image](https://user-images.githubusercontent.com/181293/59110884-47619300-8940-11e9-8d93-0955e0ec686c.png)

How can I help the analyser - in this case, telling him that *"trust me, the assigned field `.start` of the `dev` variable from the call to `ambapp_find_apbslv` is a valid pointer to a memory-mapped HW structure of "LEON3_Timer_Regs_Map" size*? I am basically asking for something like a FRAMA-C contract indicating "trust me, the area between `dev.start` and `dev.start + sizeof(LEON3_Timer_Regs_Map)` is valid".

I'll continue trying the rest of the steps first chance I get - many thanks for your help.

**Comment by arthaud** [comment]
> Your detailed answer is very much appreciated - and perhaps deserves to exist as part of the documentation?

Good idea, I will do that soon.

> How can I help the analyser - in this case, telling him that _"trust me, the assigned field `.start` of the `dev` variable from the call to `ambapp_find_apbslv` is a valid pointer to a memory-mapped HW structure of "LEON3_Timer_Regs_Map" size_? I am basically asking for something like a FRAMA-C contract indicating "trust me, the area between `dev.start` and `dev.start + sizeof(LEON3_Timer_Regs_Map)` is valid".
> 
> I'll continue trying the rest of the steps first chance I get - many thanks for your help.

**If dev.start has a pointer type:**
You could write a "stub" for `ambapp_find_apbslv`:

```c
#include <ikos/analyzer/intrinsic.h>
#include <stdlib.h>

int ambapp_find_apbslv(void*, int, int, struct ambapp_apb_info* dev) {
  // dev->start should point to a block of memory, simulate this with a malloc()
  void* ptr = malloc(sizeof(LEON3_Timer_Regs_Map));
  __ikos_assume(ptr != NULL);
  dev->start = ptr;
  return __ikos_nondet_int(); // random integer
}
```

Here we are using `malloc` to make IKOS think that `dev.start` points to a block of memory of a given size. You could also use a static variable:

```c
#include <ikos/analyzer/intrinsic.h>
#include <stdlib.h>

// Alternative implementation
int ambapp_find_apbslv(void*, int, int, struct ambapp_apb_info* dev) {
  static LEON3_Timer_Regs_Map m; // This is zero-initialized
  // Make IKOS believe it contains random values
  __ikos_forget_mem(&m, sizeof(LEON3_Timer_Regs_Map));
  dev->start = &m;
  return __ikos_nondet_int();
}
```

**If dev.start has an integer type:**
We have to use another strategy here because casting a pointer to an integer will confuse IKOS.
In that case, we could use what we called "hardware addresses", see [analyzer/README.md#hardware-addresses](https://github.com/NASA-SW-VnV/ikos/tree/master/analyzer#hardware-addresses)
Using the `--hardware-addresses` parameter, you can tell IKOS that a specific range of addresses are readable/writeable.
For instance, let's assume that the structure `LEON3_Timer_Regs_Map` is at address `0x8000300` and has a size of `0x42`.

You will first need to write a stub for `ambapp_find_apbslv`. In that case, it should be:
```c
#include <ikos/analyzer/intrinsic.h>

int ambapp_find_apbslv(void*, int, int, struct ambapp_apb_info* dev) {
  dev->start = 0x8000300;
  return __ikos_nondet_int();
}
```

You can then analyze your code with `ikos --hardware-addresses=0x8000300-0x8000342`.

**There might be another way** using `__ikos_assume_mem_size`:
https://github.com/NASA-SW-VnV/ikos/blob/c344b9267bf749128a37bcc5efb4e72411c2e992/analyzer/include/ikos/analyzer/intrinsic.h#L100-L101
This requires a pointer already pointing to a valid memory location, so this won't work in your case, because `dev.start` is completely unknown for IKOS. You really need to help him by writing a stub/contract for `ambapp_find_apbslv`.

Hopefully this should help you prove that this code is safe!

**Comment by arthaud** [comment]
I added most of my comments to the documentation in f6393c30a9b95e82add26283d00a21e994f01119 and 285479217f3ea61ffe0c753b9626c8c3d5d9330d.

Do you have other questions or remarks?

**Comment by ttsiodras** [comment]
No Maxime, no other questions - thanks for your feedback!

P.S. Had a teleconf last week with the IV&V group from NASA, where among other things we also talked about IKOS (and in fact, I told them about my experiences using the tool - and pointed them to this specific discussion for details on the how-to).
