### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by gitrj95** [NASA-SW-VnV/ikos#191]
hi. which set of docs are relevant wrt the installation? there are two installation paths that appear to be distinct--one in docs and another in the main readme. which is appropriate? i haven't had luck with either

**Comment by arthaud** [comment]
Hello,

What operating system are you using?

Under https://github.com/NASA-SW-VnV/ikos/tree/master/doc/install there are installation instructions for a few operating systems.

If yours is not there, then it means it's not officially supported. You can try https://github.com/NASA-SW-VnV/ikos/blob/master/doc/install/ROOTLESS.md as a last resort.

Unfortunately, there is also a chance that some installation instructions are broken, because this tool is not heavily maintained (to put it lightly).

**Comment by gitrj95** [comment]
i'm on fedora 34 and using the guide in docs. make breaks without much logging as to the error

**Comment by gitrj95** [comment]
are there any updates?

**Comment by arthaud** [comment]
Please provide your logs (each command you ran and their output), otherwise we cannot help you.

**Comment by gitrj95** [comment]
sure. will do
