### ISSUE TITLE
Assertion failed: (ar_cst), function translate_constant, file frontend/llvm/src/import/constant.cpp, line 200

### ISSUE THREAD

**Issue by myfreeweb** [NASA-SW-VnV/ikos#22]
The following code: https://github.com/myfreeweb/soad/blob/ef9b4e93ad02f66825c4174de4e38fc3174ee29b/soad.c

Apparently has some kind of integer constant ikos doesn't like:

```
(lldb) p *cst
error: ikos-analyzer 0x02dedb51: DW_TAG_inheritance failed to resolve the base class at 0x02dedbd3 from enclosing type 0x02dedb48.
Please file a bug and attach the file at the start of this error message
(llvm::Constant) $0 = {
  llvm::User = {
    llvm::Value = {
      VTy = 0x00000008017c96c8
      UseList = 0x00000008017dfc90
      SubclassID = '\r'
      HasValueHandle = '\0'
      SubclassOptionalData = '\0'
      SubclassData = 0
      NumUserOperands = 0
      IsUsedByMD = 0
      HasName = 0
      HasHungOffUses = 0
      HasDescriptor = 0
    }
  }
}
(lldb) p *cst->VTy
(llvm::Type) $1 = {
  Context = 0x00007fffffffc7f0
  ID = IntegerTyID
  SubclassData = 32
  NumContainedTys = 0
  ContainedTys = 0x0000000000000000
}
```

(or maybe this is caused by other weird bugs.. running on FreeBSD 13-current with system llvm70, most programs are causing failures)

**Comment by arthaud** [comment]
Hi @myfreeweb,

I tried on macOS and I got the error `No POSIX clock?!`,
so I pulled a Debian 8 docker container, and it works just fine:

```
root@1e65cc652ec1:~# ikos soad.c
[*] Compiling soad.c
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
[*] Running liveness analysis
[*] Running fixpoint profile analysis
[*] Running interprocedural value analysis
[*] Analyzing entry point: main
[*] Checking properties and writing results for entry point: main

# Time stats:
clang        : 0.055 sec
ikos-analyzer: 0.028 sec
ikos-pp      : 0.009 sec

# Summary:
Total number of checks                : 157
Total number of unreachable checks    : 0
Total number of safe checks           : 122
Total number of definite unsafe checks: 0
Total number of warnings              : 35

The program is potentially UNSAFE

# Results
Report is too big (> 15 entries)

Use `ikos-report output.db` to examine the report in your terminal.
Use `ikos-view output.db` to examine the report in a web interface.
```

I don't really know how to reproduce your bug.


Could you try to send me the llvm bitcode generated from `soad.c`? You can use 
> ikos soad.c --save-temps --temp-dir=.

and please send me both `soad.bc` and `soad.pp.bc`. Thanks.

**Comment by myfreeweb** [comment]
https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/soad.bc / https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/soad.pp.bc

This is actually probably a symptom of a more fundamental bug that happens only on FreeBSD

**Comment by arthaud** [comment]
As you said, it's probably a problem on FreeBSD.
I still can't reproduce the bug using the provided llvm bitcode files.
I guess I have to get my hands on a FreeBSD. Is it easy to install in a virtual machine using Virtualbox?

**Comment by arthaud** [comment]
I managed to compile IKOS on FreeBSD 12.0
I had to install the following packages: `bash py27-sqlite3 cmake gmp boost-libs sqlite3 llvm70`
I'm using `cmake DLLVM_CONFIG_EXECUTABLE=/usr/local/llvm70/bin/llvm-config ..`

I got segmentation faults when running IKOS. I spent my whole day trying to figure this out.

I found out that `ar::IntegerConstant* ar::ContextImpl::integer_cst()` returns wrong pointers.
The internal map `ar::ContextImpl::_integer_constants` seems fine, but when returning `it->second.get()` something weird happens.

`ar::ContextImpl::_integer_constants` is a `boost::container::flat_map` and stores its elements as contiguous `boost::dtl::pair< Key, Value >`, but the flat_map iterator returns a `std::pair< Key, Value >`, which is suspicious.

And for some crazy reasons, `boost::dtl::pair` and `std::pair` have different memory layouts on FreeBSD!

See https://reviews.llvm.org/D25389

In `std::pair`, we are getting an additional padding of 8 bytes before the first element!
```c++
IntegerConstant* ContextImpl::integer_cst(IntegerType* type, MachineInt value) {
  auto it = this->_integer_constants.find(std::make_pair(type, value));
  if (it == this->_integer_constants.end()) {
    // ...
  } else {
    printf("%p\n", &(*it));
    printf("%p\n", &(*it).first);
    return it->second.get();
  }
}
```
Output:
```
0x8018473e0
0x8018473e8
```

It looks like a bug in clang. With EBO (Empty Base Optimization), the base class `__non_trivially_copyable_base` should be optimized out, and we shouldn't have this padding of 8 bytes.

So, since `boost::dtl::pair` doesn't have this weird padding, we basically have a buffer overflow. We read at `*(p+8)` instead of `*p` inside `ar::ContextImpl::_integer_constants`.

I tried to reproduce this with a small c++ code without success..

**Comment by myfreeweb** [comment]
wow, thanks for this investigation!

> reproduce this with a small c++ code

Looks like `std::pair`s nested in each other produce an extra element:

```c++
sizeof(pair<pair<char, char>, char>) // 4
sizeof(pair<dtl::pair<char, char>, char>) // 3
sizeof(dtl::pair<pair<char, char>, char>) // 3
sizeof(dtl::pair<dtl::pair<char, char>, char>) // 3
```

**Comment by myfreeweb** [comment]
Replacing `std::pair` with `dtl::pair` in these `flat_map`s does make ikos work!

**Comment by arthaud** [comment]
Thank you for finding out that the problem is with nested `std::pair`!

I will open a bug report on boost, since they are assuming that `std::pair` and `boost::dtl::pair` have the same layout, and using nasty reinterpret_casts:
https://github.com/boostorg/container/blob/develop/include/boost/container/flat_map.hpp#L66
https://github.com/boostorg/container/blob/develop/include/boost/container/flat_map.hpp#L1306

I will also open a bug on clang/libc++ since the padding is probably not necessary.

In the meantime, I could fix IKOS by using `boost::container::dtl::pair` with a comment referring to this issue. What do you think?

**Comment by myfreeweb** [comment]
Yeah, the linked patch https://reviews.freebsd.org/P243 does that, if you can just do that in the main ikos repo, that would be great

**Comment by yurivict** [comment]
Just make a release that contains the fix. It's wrong IMO to patch non-OS-specific problems like this in individual systems, like ```P243``` above does.

**Comment by arthaud** [comment]
We will make a new release in a few weeks, after we fixed most of the Github issues.

By the way, the bug is not due to IKOS, and is pretty OS specific since it only happens on FreeBSD.

**Comment by arthaud** [comment]
I opened https://bugs.llvm.org/show_bug.cgi?id=40230, and R. Smith confirmed it's a bug in libc++.
