### ISSUE TITLE
Please respect the standard cmake BUILD_SHARED_LIBS variable

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#34]
Currently you install static libraries:
```
lib/libikos-ar.a
lib/libikos-llvm-to-ar.a
lib/libikos-pp.a
```

**Comment by arthaud** [comment]
Hi @yurivict,

I already tried to support `-DBUILD_SHARED_LIBS=ON` a few weeks ago.
I got into a lot of trouble.

On most operating systems, LLVM is distributed with static libraries (even on Linux).
The problem is that LLVM uses static initializers for its command line options.
See https://lists.llvm.org/pipermail/llvm-dev/2014-August/075855.html

When you try to compile `libikos-llvm-to-ar` or `libikos-pp` as shared libraries, some static initializers of global variables of LLVM are put into the shared library.
Then, cmake links `ikos-analyzer` with both `libikos-llvm-to-ar` and LLVM, it compiles fine but at runtime you get random crashes because these static initializers are run twice.
If you try to link `ikos-analyzer` with `libikos-llvm-to-ar` only (and not LLVM), you get link errors because you are missing some LLVM symbols. Same thing if you try to compile `libikos-llvm-to-ar` without linking LLVM.


I don't know what to do with this.


If you want to see the errors, grep `add_library` in the repository and remove the `STATIC` keyword.

By the way, since no one uses these libraries except ikos, there is no point generating shared libraries for now.

I know that static libraries are not really appreciated on some operating systems (e.g, Linux). In that case, you can just remove these files. They are not necessary to run the analyzer.

**Comment by yurivict** [comment]
Ok, thank you for your explanation!

**Comment by arthaud** [comment]
I tried this again, and this is the error I'm getting:
```
$ ikos test-1.c
[*] Compiling test-1.c
[*] Running ikos preprocessor
Two passes with the same argument (-domtree) attempted to be registered!
```

See https://stackoverflow.com/questions/17953156/cannot-use-libclang-with-qt

**Comment by yurivict** [comment]
No, it's ok, if this is too difficult - no need to waste time on this.

**Comment by arthaud** [comment]
IKOS can now be built with shared libraries using `-DBUILD_SHARED_LIBS=ON`.

Please note that most package managers provide LLVM as a set of static libraries. Building IKOS with shared libraries while linking with LLVM static libraries will result into errors such as `Two passes with the same argument (-domtree) attempted to be registered`. To fix this, add the parameter `-DIKOS_LINK_LLVM_DYLIB=ON` to link against libLLVM shared library.

**Note to packagers:**
If you are packaging the analyzer itself, you should compile with `BUILD_SHARED_LIBS=OFF` (the default) for better performance.

Then, you can discard the following files:
- lib/*.a
- include/ikos/ar/*
- include/ikos/core/*
- include/ikos/frontend/*

These are only necessary for tools that want to be built on top of IKOS. They should go in a different package, for instance `ikos-dev`.

**Comment by yurivict** [comment]
@arthaud  Thank you for fixing it!

Build breaks with clang now:
```
/usr/ports/devel/ikos/work/ikos-2.1-32-g54500c4/frontend/llvm/src/import/type.cpp:396:14: error: member reference base type 'long' is not a structure or union
    if (count.is< llvm::ConstantInt* >() &&
        ~~~~~^~~
/usr/ports/devel/ikos/work/ikos-2.1-32-g54500c4/frontend/llvm/src/import/type.cpp:396:38: error: expected expression
    if (count.is< llvm::ConstantInt* >() &&
                                     ^
```
