### ISSUE TITLE
error: llvm::DICompositeType with DW_TAG_array_type tag and llvm::StructType have a different number of elements

### ISSUE THREAD

**Issue by practicalswift** [NASA-SW-VnV/ikos#46]
```
$ cat testcase.cpp
struct i {
  unsigned j[16];
} k[]{{}, {2}};
$ clang++ -c testcase.cpp
$ ikos testcase.cpp
[*] Compiling testcase.cpp
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
ikos-analyzer: …: error: llvm::DICompositeType with DW_TAG_array_type tag and llvm::StructType have a different number of elements
ikos: error: a run-time error occured
```

**Comment by gregsq** [comment]
I hope I can add some helpful notes here. Having said that, this is my first look at llvm, so please ignore the naive parts.
.
Initialized variables are described more specifically in the emitted LLVM output. The llvm::type as used for a array can be either an array, or a struct tagged as defining the layout. Examples for initialized and partially initialized declarations follow. 

```
struct i {
  unsigned j[16];
} k[]{{0},{0}}; // Later the same as uninitialized - {[16 * i32]}
```

Gives

```
; ModuleID = 'testcase.cpp'
source_filename = "testcase.cpp"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.i = type { [16 x i32] }

@k = global [2 x %struct.i] zeroinitializer, align 16
```

While ( for example )
```
struct i {
  unsigned j[16];
} k[]{{0},{1}}; // split layout ( i32 and [15 x i32] ) * 2 )

```
Gives

```
; ModuleID = 'testcase.cpp'
source_filename = "testcase.cpp"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.i = type { [16 x i32] }

@k = global <{ %struct.i, { <{ i32, [15 x i32] }> } }> <{ %struct.i zeroinitializer, { <{ i32, [15 x i32] }> } { <{ i32, [15 x i32] }> <{ i32 1, [15 x i32] zeroinitializer }> } }>, align 16

```
A few comments:
As more initializer values are given to k's initializer list, the structure contains structures that show the layout disposition. Eg, ( [16 x i32] ,,{i32, [15 x i32])..(i32 i32, [14 x i32]).

The number of structure segments ( 2 ) != the expected count of the array type ( 16 ), which then fails the test for this testcase.

The < layout specification > ( if that's the right term ) contains implied zeroinit or specific init values ( by providing them after the i32 declaration ) for each list initializer element. This I presume will affect numerical range analysis.

It appears that there would be quite a few bugs that would be quashed once this is fixed. 
Hope this is of some help

**Comment by arthaud** [comment]
Thanks @gregsq for the investigation.

To give the big picture:
The source of most of the bugs reported here in the last few weeks is the translation from LLVM to AR (our internal representation of the source code). The analysis using Abstract Interpretation requires to know the signedness (signed/unsigned) of integers, so our internal representation has signs information (e.g, `si32` vs `ui32`).

The problem is that the LLVM representation does not have sign information (i.e, they just have `i32`). Thus, we decided to recover sign information using LLVM debug information. For that, we have to dive into the debug information and match it with the LLVM type. This is mostly a workaround and is probably not recommended by LLVM developers.

In most cases we can recover the integer signs but sometimes we have discrepancies between the LLVM type and the debug information.

This is what is happening here.
The LLVM type is: `<{ i32, [15 x i32] }>`
The LLVM debug info is:
```
!10 = !DICompositeType(tag: DW_TAG_array_type, baseType: !11, size: 512, elements: !12)
!11 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!12 = !{!13}
!13 = !DISubrange(count: 16)
```

It seems like I will need to add another workaround. It is surprising that LLVM transforms `[16 x i32]` into `<{ i32, [15 x i32] }>`

NB: See https://lists.llvm.org/pipermail/llvm-dev/2011-November/044923.html

**Comment by practicalswift** [comment]
Confirming that I'm no longer hitting this issue. Thanks for fixing!
