### ISSUE TITLE
Analysis via ikos-scan does not give same same result as analysis using ikos

### ISSUE THREAD

**Issue by practicalswift** [NASA-SW-VnV/ikos#65]
Preparation:

```
$ git clone https://github.com/sipa/minisketch minisketch-ikos
$ cd minisketch-ikos/src/
```

Analysis of `test-exhaust` via `ikos-scan`:

```
$ ikos-scan make
…
Analyze test-exhaust? [Y/n]
…
[*] Translating LLVM bitcode to AR
…
ikos: error: a run-time error occurred
```

Analysis of `test-exhaust` using `ikos` directly:

```
$ ikos test-exhaust.cpp
…
[*] Translating LLVM bitcode to AR
…
Use `ikos-report output.db` to examine the report in your terminal.
Use `ikos-view output.db` to examine the report in a web interface.
```

Analysis of `test-exhaust` using `ikos` after manual preprocessing:

```
$ clang-cpp-7 test-exhaust.cpp > test-exhaust-after-cpp.cpp
$ ikos test-exhaust-after-cpp.cpp
…
[*] Translating LLVM bitcode to AR
…
Use `ikos-report output.db` to examine the report in your terminal.
Use `ikos-view output.db` to examine the report in a web interface.
```

**Comment by arthaud** [comment]
Hi @practicalswift,

This might be surprising but it is normal.

**The first method**: `ikos-scan make`
It compiles all the .cpp files and links them, generating a `test-exhaust.bc` of 130MB. This is the recommended method.

**The second method**: `ikos test-exhaust.cpp`
It only compiles `test-exhaust.cpp` using:
```
clang -c -emit-llvm -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -g -O0 -Xclang -disable-O0-optnone test-exhaust.cpp -o test-exhaust.bc -isystem $ikos_install/include -fcolor-diagnostics -std=c++17
```
The resulting `test-exhaust.bc` is only 571K. It misses a lot of code (basically everything that is in `libminisketch_test.a`).

**The third method**: `clang-cpp-7 test-exhaust.cpp > test-exhaust-after-cpp.cpp; ikos test-exhaust-after-cpp.cpp`
As you saw in the second method, IKOS compiles your code with `-D_FORTIFY_SOURCE=0`.
Since you are doing the preprocessing yourself without `-D_FORTIFY_SOURCE=0`, the preprocessed code will be different, thus generating different results.

I hope this makes sense to you.

**Comment by practicalswift** [comment]
Makes perfect sense. Thanks for the clarification. Closing!
