### ISSUE TITLE
False positive in the iostream standard library [2]

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#81]
This code
```
#include <string>
#include <iostream>

int main() {
  std::string str;
  str = "Hello World!\n";
  std::cout << str;
}
```
triggers a lot of warnings like this:
```
/usr/include/c++/v1/locale: In function 'std::__1::ostreambuf_iterator<char, std::__1::char_traits<char>> std::__1::__pad_and_output<char, std::__1::char_traits<char> >(std::__1::ostreambuf_iterator<char, std::__1::char_traits<char>>(std::__1::ostreambuf_iterator const*, std::__1::ostreambuf_iterator const*, std::__1::ostreambuf_iterator const*, std::__1::ios_base&, std::__1::ostreambuf_iterator)':
/usr/include/c++/v1/ios:512:14: warning: possible buffer overflow, pointer '&this->__width_' points to global variable 'std::__1::cout' of size 156 bytes
    __width_ = __wide;
             ^
```

FreeBSD 11.2 amd64

**Comment by arthaud** [comment]
Please see my comment in issue [#88](https://github.com/NASA-SW-VnV/ikos/issues/88#issuecomment-454208891)

**Comment by ivanperez-keera** [comment]
This bug has been open for almost 5 years.

Given the resources available and current priorities, I suspect this will be unlikely to be fixed.

Rather than keeping this open indefinitely, I suggest we either close it altogether, or add documentation regarding IKOS' limitations if anything is incomplete. Such documentation could be in the README, or TROUBLESHOOTING, or just github discussions (IMO issues should be reserved for things we are actively working towards).

**Comment by ivanperez-keera** [comment]
Based on the comment above, I am closing this. If you disagree, please re-open it. Thanks!
