### ISSUE TITLE
Misses the uninitialized field error

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#84]
This testcase
```
#include <stdio.h>
  
class X {
public:
  int y;
  X() { }
};

int main(int argc, char *argv[]) {
  X x;
  printf("%d\n", x.y);
  return 0;
}
```
uses the uninitialized field ```X::y``` and ikos doesn't notice this.

**Comment by arthaud** [comment]
Hi @yurivict,

The uninitialized variable analysis is currently disabled.

Use the parameter `-a=uva` or `-a='*'` to enable it:
```
$ ikos -a='*' test.cpp
[*] Compiling test.cpp
[*] Running ikos preprocessor
[*] Running ikos analyzer
[!] ikos was compiled in debug mode, the analysis might be slow
[*] Translating LLVM bitcode to AR
[*] Running liveness analysis
[*] Running fixpoint profile analysis
[*] Running interprocedural value analysis
[*] Analyzing entry point: main
[*] Checking properties and writing results for entry point: main

# Time stats:
clang        : 0.137 sec
ikos-analyzer: 0.021 sec
ikos-pp      : 0.020 sec

# Summary:
Total number of checks                : 8
Total number of unreachable checks    : 0
Total number of safe checks           : 7
Total number of definite unsafe checks: 0
Total number of warnings              : 1

The program is potentially UNSAFE

# Results
test.cpp: In function 'main':
test.cpp:11:3: warning: expression 'x.y' might be uninitialized
  printf("%d\n", x.y);
  ^
```

We decided to disable the uninitialized variable analysis by default because it produces a high rate of false positives, adding a lot of noise to the tool, making the results worthless.

For example, on the following code:
```c
#include <stdio.h>
#define N 10

int main() {
    int tab[N];
    for (size_t i=0; i<N; i++) {
        tab[i] = i;
    }
    printf("%d", tab[N-1]);
    return 0;
}
```

`ikos -a='*' test.c` produces the following warning:
```
test.c: In function 'main':
test.c:9:5: warning: expression 'tab[9]' might be uninitialized
    printf("%d", tab[N-1]);
    ^
```

This code is perfectly safe, of course. It follows strict coding rules for critical software, but IKOS is not able to prove that it is safe because of the uninitialized variable analysis.

We tried to solve this but it appears to be hard to do with Abstract Interpretation, the theory used in IKOS. We would need to infer that the loop initializes the elements from `0` to `i`, so at the end of the loop, all the array is initialized. I found a few research publications about "array smashing" that could help but it is hard to implement.

**Comment by arthaud** [comment]
This is tracked by #99.
