### ISSUE TITLE
Bogus error "pointer is null"

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#85]
In amalgamated SQLite source https://www.sqlite.org/2018/sqlite-amalgamation-3260000.zip, ikos prints a bogus error for shell.c:
```pointer 'pzErrmsg' is null
shell.c:6839:13: error: pointer 'pzErrmsg' is null
  *pzErrmsg = sqlite3_mprintf("%s", sqlite3_errmsg(db));
            ^
```
for this code:
```
static void idxDatabaseError(
  sqlite3 *db,                    /* Database handle */
  char **pzErrmsg                 /* Write error here */
){  
  *pzErrmsg = sqlite3_mprintf("%s", sqlite3_errmsg(db));
} 
```

It can't be generally ```null```. If it is ```null``` in some invocations, ikos should list these invocations.

**Comment by arthaud** [comment]
Hi @yurivict,

I believe the problem is similar to #80.

Did you just run `ikos shell.c`?

If so, IKOS doesn't have the source code of most of the `sqlite3_` functions implemented in `sqlite3.c`

You should get warnings such as:
```
ignored possible side effect of function call, could not infer information about XXX. Analysis might be unsound.
```

Since ikos doesn't have the source code of these functions, it assumes `*pzErrmsg` is null.

To analyze the whole project, use:
```
$ PATH="/path/to/llvm7/bin:$PATH"
$ clang -c -emit-llvm -Wall -D_FORTIFY_SOURCE=0 -g -O0 -Xclang -disable-O0-optnone shell.c -o shell.c.bc
$ clang -c -emit-llvm -Wall -D_FORTIFY_SOURCE=0 -g -O0 -Xclang -disable-O0-optnone sqlite3.c -o sqlite3.c.bc
$ llvm-link shell.c.bc sqlite3.c.bc -o shell.bc
$ ikos shell.bc
```
The analysis will probably take a while.

**Comment by yurivict** [comment]
Thank you for this explanation.
