### ISSUE TITLE
False positive in the iostream standard library [1]

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#88]
This code
```
class AOut : public std::ostringstream {
public:
  ~AOut() {
    std::cout << str();
  } 
};
```
triggers these bogus warnings:
```
main.cpp: In function 'AOut::~AOut(void)':
main.cpp:111:11: warning: pointer '(int64_t*)(&(*((int8_t**)this))[-24])' might be null
  ~AOut() {
          ^
main.cpp: In function 'AOut::~AOut(void)':
main.cpp:111:11: warning: memory access might be unsafe, could not infer information about pointer '(int64_t*)(&(*((int8_t**)this))[-24])'
  ~AOut() {
          ^
main.cpp: In function 'AOut::~AOut(void)':
main.cpp:111:11: warning: possible buffer overflow, pointer '(int32_t()***)(&((int8_t*)this)[*((int64_t*)(&(*((int8_t**)this))[-24]))])' points to local variable '__t' of size 264 bytes
  ~AOut() {
          ^
```

**Comment by arthaud** [comment]
Hi @yurivict,

Analyzing C++ code using the STL is pretty hard and currently triggers a lot of false positives. Your code might be 6 lines long, but after running the preprocessor, it is actually 33972 lines long (excluding blank lines) on my laptop. This is a huge pile of code with a lot of optimizations that is hard to prove.

For instance, `std::string` uses [small buffer optimization](https://akrzemi1.wordpress.com/2014/04/14/common-optimizations/), implemented with a union. This is not handled well by Abstract Interpretation since you need a disjonction.

Standard streams (e.g, `ostringstream`) are also complicated because they use virtual inheritance. This makes the memory layout pretty complex, and this is why you get warnings about `(int64_t*)(&(*((int8_t**)this))[-24])`.

As a general note, we do not consider the analysis of C++ a priority. IKOS was designed to prove safety critical codes at NASA. These are mostly in C and have strict coding rules (for example, no dynamic memory allocation).

Of course, feel free to open other issues about the analysis of C++, we will look at them after we fixed all the other issues. Also note that even if I investigate these issues, I might not have solutions to them.

**Comment by ivanperez-keera** [comment]
This bug has been open for almost 5 years.

Given the resources available and current priorities, I suspect this will be unlikely to be fixed.

Rather than keeping this open indefinitely, I suggest we either close it altogether, or add documentation regarding IKOS' limitations if anything is incomplete. Such documentation could be in the README, or TROUBLESHOOTING, or just github discussions (IMO issues should be reserved for things we are actively working towards).

**Comment by ivanperez-keera** [comment]
Based on the comment above, I am closing this. If you disagree, please re-open it. Thanks!
