### ISSUE TITLE
ikos-analyzer only analyzing objects with a `main` entrypoint

### ISSUE THREAD

**Issue by coderobe** [NASA-SW-VnV/ikos#90]
Is it by design, or maybe an implementation limitation, that ikos will only analyze objects containing an entrypoint `main` function?
This prevents ikos from e.g. analyzing program libraries or other objects that don't provide a standard `main` entrypoint.

Attempting to analyze a shared-object build of a library program results in the following:
```
Analyze libkitchensink.so.0.1.0? [Y/n] y
[*] Running ikos libkitchensink.so.0.1.0.bc -o libkitchensink.so.0.1.0.db
[*] Running ikos preprocessor
[*] Running ikos analyzer
[*] Translating LLVM bitcode to AR
ikos-analyzer: /tmp/ikos-gn7vzgq8/libkitchensink.so.0.1.0.pp.bc: error: could not find function 'main'
ikos: error: a run-time error occurred
```

**Comment by Harvesterify** [comment]
You can manually provide an entry point by using the "--entry-points xxx" flag.

For the example code given in the documentation (loop.c):

```
#include <stdio.h>
int a[10];

int test(int argc, char *argv[]) {
    size_t i = 0;
    for (;i < 10; i++) {
        a[i] = i;
    }
    a[i] = i;
    printf("%i", a[i]);
}
```

You would call IKOS using this command line : `ikos loop.c --entry-points test`

**Comment by practicalswift** [comment]
One usability improvement I've thought about: in the absence of `main`, what about auto-detecting the entry-points? The auto-detection could be as simple as adding all functions declared in the file as entry-points.

When I've been using `ikos` on files without a `main` function that's the behaviour I've wanted.

FWIW, having it defaulted would save me a lot of keystrokes and numerous trips to the GitHub page to look up the proper argument name (`--entry-points`) :-)

What would be the pros/cons of such a change?

**Comment by arthaud** [comment]
Hi @coderobe,

This is indeed by design.

The default analysis is **interprocedural**, it starts from main and dives into the function calls. This method provides the best results since it infers a very good invariant about the context (e.g, function parameters and global variables) as we dive into functions.

As an alternative, you can use the **intraprocedural** analysis using `ikos --proc=intra`. This will analyze each function independently from each other. This should work on a shared library. You will probably get a lot of false positives, since ikos won't make any assumptions about the function parameters and global variables.

For instance, with the following code:
```c
void f(int* p) {
  *p = 1;
}
```
ikos will raise a warning since `p` could be null.
Of course, we could fix this with:
```c
void f(int* p) {
  if (p != NULL) {
    *p = 1;
  } 
}
```
ikos will now raise a warning about a possible buffer overflow since we don't know where `p` points to.
We could assume `p` points to a symbolic location of size int, but then we could have issues with aliasing pointers.

And there will be no way to prove that the following code is safe:
```c
void f(int* p, int n) {
  if (p != NULL) {
    p[n] = 0;
  }
}
```
This would require extra information from the user (usually called function contracts, or annotations), and we don't handle that currently.

@practicalswift:  I don't think I've ever tried the interprocedural analysis with all functions as entry points. I imagine this generates a lot of redundant warnings. IKOS merges the warnings that are on the same instructions before reporting them to the user, so this helps.

Still, you will get false positives, for instance:
```c
void f(int* p) {
  *p = 1;
}
void g() {
  int x;
  f(&x);
}
```
You will get a false positive since `f` is a entry point, `*p = 1` cannot be proven safe since we don't have information on `p`. From the entry point `g`, this code is safe.

@practicalswift: I don't think it should be the default behavior. I would rather have the user understand the different types of analysis so they can make his own decision. I could implement something like `--entry-points=*' if it helps.

To analyze a library, I would recommend to write a small `main` function that uses the library and uses random inputs. This will give the best precision but I agree this can be cumbersome for a big library.

**Comment by practicalswift** [comment]
@arthaud Good points! `--entry-points=*` would be nice! I'm opening an issue for that.

**Comment by arthaud** [comment]
I'm closing this since the discussion seems done.

Feel free to open another issue if you have any suggestion (like #93).
