### ISSUE TITLE
ikos-scan fails: Nothing to analyze.

### ISSUE THREAD

**Issue by yurivict** [NASA-SW-VnV/ikos#98]
I tried ```ikos-scan``` on https://github.com/hyattpd/Prodigal, but it failed:
```
Nothing to analyze.
```

It is a simple C project with several source files, so it should be able to analyze it.

**Comment by arthaud** [comment]
This works perfectly on macOS.

The problem is probably that their [Makefile](https://github.com/hyattpd/Prodigal/blob/GoogleImport/Makefile) defines `CC = gcc`. `ikos-scan` needs to override `CC` and `CXX` to catch the compilation commands.

`ikos-scan` automatically adds the option `-e` ("specify that environment variables override macro assignments within makefiles") when running `ikos-scan make`. This works fine on Mac and Linux, I don't know about FreeBSD.

What command are you running? Could you try `ikos-scan -vvv make`?

**Comment by yurivict** [comment]
Sorry, I forgot to tell you that I replaced gcc with cc.

```
$ ikos-scan -vvv gmake
[.] Running gmake
cc -pedantic -Wall -O3 -c -o bitmap.o bitmap.c
cc -pedantic -Wall -O3 -c -o dprog.o dprog.c
cc -pedantic -Wall -O3 -c -o gene.o gene.c
cc -pedantic -Wall -O3 -c -o main.o main.c
cc -pedantic -Wall -O3 -c -o metagenomic.o metagenomic.c
cc -pedantic -Wall -O3 -c -o node.o node.c
cc -pedantic -Wall -O3 -c -o sequence.o sequence.c
cc -pedantic -Wall -O3 -c -o training.o training.c
cc -pedantic -Wall -O3 -o prodigal bitmap.o dprog.o gene.o main.o metagenomic.o node.o sequence.o training.o -lm 
Nothing to analyze.
```

**Comment by arthaud** [comment]
Thanks. Could you try `ikos-scan -vvv gmake -e`?

**Comment by yurivict** [comment]
It does analyze with ```-e```.
